---
title: "Merging-processed-data"
author: "A.Lofstedt"
date: "2023-01-06"
output: html_document
---

```{r setup, include=FALSE}
# sets options for entire document in the first chunk
knitr::opts_chunk$set(echo = TRUE)
```

## Part 2: Merging processed data to map UK seafood supply chains

This R Markdown document (part 2) outlines how the data processed is merged together.

## Preparation

```{r Load libraries, include=FALSE}
# Load packages
library(tidyr) # for tidying data
library(dplyr) # base R alternative but neater
library(vroom) # for loading and transforming data
library(tidyverse) # data exploration 
library(reshape2) # for melting data frames i.e. short and wide to long and thin
library(data.table) # for fread()-function
library(mice) # md.pattern to show missing data
library(stringr) # used to replace matched patterns in a string

```

```{r Load file path, echo=TRUE}
# Loading file path to the data into a value 
source("Data_filepath.R")# Data_filepath.R is listed in .gitignore-file. So, you will need to create that file yourself and provide your respected filepath using "data_dir <- [enter your here]"
```


```{r Specify the desired file path}
filepath <- paste(data_dir,"ProcessedData", sep = "") 
# note we are able to change this to another file e.g. saving the output
```


```{r Load cleaned data}
# Load UK capture production data 
df_captureProd_NS_clean_data <- vroom(file = paste(filepath,"CaptureProductionData_NS_clean.csv", sep = "/"))

# Load UK aquaculture production data 
df_aquaProd_Eurostat_clean_data <- vroom(file = paste(filepath,"AquacultureData_Eurostat_clean.csv", sep = "/"))

# Load UK trade data (further processed)
df_trade_HMRC_clean_data <- vroom(file = paste(filepath,"Trade_HMRC_clean.csv", sep = "/"))

# Load UK household purchasing data 
df_housePurch_DEFRA_clean_data <- vroom(file = paste(filepath,"HouseholdPurchases_DEFRA.csv", sep = "/"))

# Load UK eating out purchasing data 
df_eatenOutPurch_DEFRA_clean_data <- vroom(file = paste(filepath,"EatenOutPurchases_DEFRA.csv", sep = "/"))

# Load UK consumption data 
df_consumption_NDNS_clean_data <- vroom(file = paste(filepath,"ConsumptionData_NDNS_clean.csv", sep = "/"))

# Load UK population data 
df_popSize_NS_clean_data <- vroom(file = paste(filepath,"PopSize_NS.csv", sep = "/"))

```


## Merge cleaned data sheets

```{r Check structure of data frames}
# Check structure of the data frames- should all have the same structure
colnames(df_captureProd_NS_clean_data)
colnames(df_aquaProd_Eurostat_clean_data)
colnames(df_trade_HMRC_clean_data)
colnames(df_housePurch_DEFRA_clean_data)
colnames(df_eatenOutPurch_DEFRA_clean_data)
colnames(df_consumption_NDNS_clean_data)
colnames(df_popSize_NS_clean_data)

```


```{r Create df of seafood supplies}
# Rbind() data frames by column names
df_UKSeafoodSupplies <- rbind(df_captureProd_NS_clean_data, df_aquaProd_Eurostat_clean_data, df_trade_HMRC_clean_data)

# Allocate population size to each year
df_UKSeafoodSupplies$popsize <- df_popSize_NS_clean_data

# Calculate g/capita/week
df_UKSeafoodSupplies$value_gweek <- (df_UKSeafoodSupplies$Value / df_UKSeafoodSupplies$popsize) * 7 

# Merge all cleaned data frames together
UK_seafood_data <- rbind(df_captureProd_NS_clean_data, df_aquaProd_Eurostat_clean_data, df_trade_HMRC_clean_data, df_housePurch_DEFRA_clean_data, df_eatenOutPurch_DEFRA_clean_data, df_consumption_NDNS_clean_data)

# Check structure of new data set
str(UK_seafood_data)

```


## Exploratory figures

```{r Figure 1. UK fish production (capture and aqaucualture data)}
# Plot UK seafood production (merge capture and aquaculture data together) 
UK_production_data <- rbind(df_captureProd_NS_clean_data, df_aquaProd_Eurostat_clean_data)

# Calculate fish produced per week 
UK_production_data$ValueGramsCapitaWeek <- UK_production_data$ValueGramsCapitaDay * 7

# Plot UK fisheries production data between 2009 and 2020
plot(aggregate(ValueGramsCapitaWeek ~ Year, data = UK_production_data, FUN = sum), xlim = c(2009, 2018), type= "l", lwd= 1.5, ylab = "UK seafood production (g/capita/week)")
```

```{r Figure 2. UK farmed salmon production}
# UK farmed salmon production
# Calculate fish produced per week
farmed_salmon <- subset(df_aquaProd_Eurostat_data, Species == "Atlantic salmon")
farmed_salmon$ValueGramsCapitaWeek <- farmed_salmon$ValueGramsCapitaDay*7

# Plot UK farmed salmon production
plot(ValueGramsCapitaWeek ~ Year, data = farmed_salmon, xlim = c(2009, 2018), type= "l",lwd= 1.5, ylab = "UK salmon production (edible portion g/capita/week)")

```

```{r Figure 3. UK cod capture production}
# UK capture cod production
# Calculate fish produced per week
wild_cod <- subset(df_wildProd_NS_data, Species == "Cod")
wild_cod$ValueGramsCapitaWeek <- wild_cod$ValueGramsCapitaDay*7

# Reorder data set according to Year
wild_cod2 <- wild_cod[order(wild_cod$Year), ]

# Plot UK farmed salmon production
plot(ValueGramsCapitaWeek ~ Year, data = wild_cod2, xlim = c(2009, 2020), type= "l", lwd= 1.5, ylab = "UK cod production (edible portion g/capita/week)")

```

```{r Figure 4. UK seafood trade}
# Subset trade data in to separate commodities 
UK_imports <- subset(df_trade_HMRC_data, Commodity == "Imports")
UK_exports <- subset(df_trade_HMRC_data, Commodity == "Exports")

plot(aggregate(ValueGramsCapitaWeek ~ Year, data = UK_imports, FUN = sum), xlim = c(2009, 2019), type= "l", lwd= 1.5, ylab = "UK fish imports (g/capita/week)")

plot(aggregate(ValueGramsCapitaWeek ~ Year, data = UK_exports, FUN = sum), xlim = c(2009, 2019), type= "l", lwd= 1.5, ylab = "UK fish exports (g/capita/week)")


# Plot on same graph
plot(aggregate(ValueGramsCapitaWeek ~ Year, data = UK_exports, FUN = sum), ylim= c(0,16), xlim = c(2009, 2019), type= "l", lwd= 1.5, ylab = "UK fish traded (g/capita/week)", col= "red") +
  lines(aggregate(ValueGramsCapitaWeek ~ Year, data = UK_imports, FUN = sum), col= "blue") + legend("topright", legend =  c("Import", "Export"), fill = c("blue", "red"))


```

```{r Figure 5. UK fish purchases (houshold and eaten out)}
# Create data frame combining fish purchase data
fish_purchases <- rbind(df_housePurch_DEFRA_data, df_eatenOutPurch_DEFRA_data)

plot(aggregate(ValueGramsCapitaDay ~ Year, data = df_housePurch_DEFRA_data, FUN = sum))
plot(aggregate(ValueGramsCapitaDay ~ Year, data = df_eatenOutPurch_DEFRA_data, FUN = sum))

# Calculate fish purchased per week
fish_purchases$ValueGramsCapitaWeek <- fish_purchases$ValueGramsCapitaDay*7

plot(aggregate(ValueGramsCapitaWeek ~ Year, data = fish_purchases, FUN = sum), xlim = c(2009, 2020), type= "l", lwd= 1.5, ylab = "UK fish purchases (g/capita/week)")

# Interesting with 2020 data- reduction in fish purchases

```



```{r Figure 6. Plot average lean fish capture production (g/capita/day) between 2009 and 2020}

# Subset lean capture fishery production in the UK
prod_lean <- subset(df_wildProd_NS_data, SACN == "Lean", select = c(Year, ValueGramsCapitaDay))

# Subset lean capture fishery production in the UK
prod_oily <- subset(df_wildProd_NS_data, SACN == "Oily", select = c(Year, ValueGramsCapitaDay))

plot(aggregate(ValueGramsCapitaDay ~ Year, data = df_wildProd_NS_data, mean)) # all fish produced 

# Plot lean fish only 
plot(aggregate(ValueGramsCapitaDay ~ Year, data = prod_lean, mean), ylim= c(0, 0.65), col= "red") + points(aggregate(ValueGramsCapitaDay ~ Year, data = prod_oily, mean), col = "blue")


plot(aggregate(ValueGramsCapitaDay ~ Year, data = prod_oily, mean))

```

### END

```{r}
# Rename species coulmn in aquculture dataset 
df_aquaProd_Eurostat_data <- rename(df_aquaProd_Eurostat_data, Species= SimplifiedSpecies)
```


```{r Identify unique species names in the data set}
# Identify unique species in the data set 
captureFish_NS <- as.data.frame(sort(unique(df_wildProd_NS_data$Species)))
farmedFish_Eurostat <- as.data.frame(sort(unique(df_aquaProd_Eurostat_data$SimplifiedSpecies)))
trade_HMRC <- as.data.frame(sort(unique(df_trade_HMRC_data$Species)))
checkSpeciesNames <- cbind(trade_HMRC, farmedFish_Eurostat, captureFish_NS)

write.csv(captureFish_NS, file= "NS_speciesNames")
write.csv(farmedFish_Eurostat, file= "Eurostat_speciesNames")
write.csv(trade_HMRC, file= "HMRC_speciesNames")

```
