---
title: "NatureFood_SeafoodFigures"
author: "Lofstedt, A."
date: "28-06-23"
output: powerpoint_presentation
---

Code for Nature Food figures only. 

### Preparation 

```{r Load libraries, include = FALSE}
# Load packages
library(tidyr) # for tidying data
library(dplyr) # base R alternative but neater
library(vroom) # for loading and transforming data
library(tidyverse) # data exploration 
library(reshape2) # for melting data frames i.e. short and wide to long and thin
library(data.table) # for fread()-function
library(mice) # md.pattern to show missing data
library(plyr) # joins multiple data frames together
library(ggplot2) # makes plots fancier
library(scales) # displays integers on the axis
library(ggthemes) # contains extra themes, scales and functions for and related to ggplot2
library(gridExtra)
library(cowplot) # Plots two figures one output
library(fmsb) # for radar plots

```


```{r Edit chunk settings, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warninf = FALSE, 
  fig.height = 9, 
  fig.width = 16
)
```


```{r Setup default for figures, include=FALSE}
# Set default presentation of figures
theme_set(theme_bw()%+replace%
            theme(
              title = element_text(size = 26), 
              text = element_text(size = 30), 
              axis.text = element_text(size = 26, colour = "gray40"), # increase to make readable
              legend.key.size = unit(1.2, "cm"), 
              legend.title = element_text(size = 26), 
              legend.text = element_text(size = 24),
              panel.grid.major = element_line(colour= "gray40", linetype = "dotted", linewidth = 0.9), 
              panel.grid.minor = element_line(colour = "gray70", linetype = "dotted", linewidth = 0.7)
            ))
# instead of "size" can also use "linewidth"
```


```{r Set colour-blind palette}
# Colour-blind friendly palette with grey. Try to keep the order (http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette)
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")
#consumption, exports, imports, production, purchases, supplies

# Colours will be allocated in commodity alphabetical order. 
```



```{r Load file path, echo=TRUE}
# Loading file path to the data into a value 
source("Data_filepath.R")# Data_filepath.R is listed in .gitignore-file. So, you will need to create that file yourself and provide your respected filepath using "data_dir <- [enter your here]"
```

```{r Specify the desired file path}
filepath <- paste(data_dir,"Outputs/Databases", sep = "") 
# note we are able to change this to another file e.g. saving the output
```

```{r Load the seafood database}
# Load database 
df_UK_seafoodDB <- vroom(file=paste(filepath,"Seafood-database_preliminary.csv", sep="/"), na = c("NA"))

df_UK_seafoodDBNC <- vroom(file=paste(filepath,"Seafood-database-PCW_composition_preliminary.csv", sep="/"), na = c("NA"))
```



```{r Load population data}
#Specify the file path
filepath <- paste(data_dir,"ProcessedData", sep = "") 

# Load database 
df_UK_population <- vroom(file=paste(filepath,"UKPopulation_ONS_PreliminaryCleaned.csv", sep="/"), na = c("NA"))

# Simplify population data
df_UK_population_simp <- df_UK_population[c("Year", "UKPOP")]

```


```{r Merge SFDB with UK population}
df_UK_seafoodDB_Y <- merge(df_UK_seafoodDB, df_UK_population_simp, "Year")
```


```{r Changing volumne units to grams/capita/week}
# Calcualte g/capita/week
df_UK_seafoodDB_PCW <- 
  df_UK_seafoodDB_Y %>% 
  mutate(Volume = Volume/UKPOP/52, Units = "g/capita/week")

# Change structure of the database (short and wide)
# Aggregate value by commodity, year and species (production data composed of aquaculture and wild capture)
df_UK_seafoodDB_PCW_simp <- aggregate(Volume ~ Commodity + Year + Species + SpeciesType + SACN, data = df_UK_seafoodDB_PCW, sum)

# Need to unstack database to calculate seafood supplied. Change structure of the dataframe- convert to wide and short
df_UK_seafoodDB_PCW_short <- df_UK_seafoodDB_PCW_simp %>%
  pivot_wider(names_from = Commodity, values_from = Volume)

# Calculate seafood supplies whilst ignoring NA values
df_UK_seafoodDB_PCW_short <- df_UK_seafoodDB_PCW_short %>% 
  mutate(Supply = Production + Imports - Exports )
```



```{r Delete later}

# Aggregate data 
df_UK_seafoodDB_PCW_test <- aggregate(Supply ~ Year + Species, data = df_UK_seafoodDB_PCW_short, sum)
df_UK_seafoodDB_PCW_test18 <- subset(df_UK_seafoodDB_PCW_test, Year == 2018)

ggplot(df_UK_seafoodDB_PCW_test18, aes(Species, Supply)) +
  geom_bar(position = "stack", stat= "identity", color = "black") +
  scale_y_continuous(name = "Amount of seafood (g/capita/week)", limits = c(0,100)) +
  scale_x_discrete(name = "Year", 
                     guide = guide_axis(angle = 45)) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  theme(legend.title = element_blank()) 

```



### Figure 1A. UK seafood supplies, consumption and purchases (g/capita/week) between 2009 and 2018.

```{r Seafood supplies consumption and purchases between 2009 and 2018}
# Subset desired variables 
df_UK_seafoodDB_PCW_shorter <- df_UK_seafoodDB_PCW_short[c("Supply", "Consumption", "Purchases", "Year", "Species", "SACN")]

# Change structure of the data set 
df_UK_seafoodDB_PCW_long <- melt(df_UK_seafoodDB_PCW_shorter, id.vars = c("Year", "Species", "SACN"), variable.name = "Commodity", value.name = "Volume")

# Aggregate data 
df_UK_seafoodDB_PCW_sum <- aggregate(Volume ~ Year + Commodity, data = df_UK_seafoodDB_PCW_long, sum)


# Plot figure. Two option below- low to high or high to low
df_UK_seafoodDB_PCW_sum$Commodity_f <-  factor(df_UK_seafoodDB_PCW_sum$Commodity, levels = c("Consumption", "Purchases", "Supply"))

# Plot total seafood supplied, purchases and consumed (g/capita/week) between 2009 and 2018. 
ggplot(df_UK_seafoodDB_PCW_sum, aes(Year, Volume, fill= Commodity_f)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_y_continuous(name = "Amount of seafood (g/capita/week)", limits = c(0,300)) +
  scale_x_continuous(name = "Year", breaks = seq(2009, 2018, 1), 
                     guide = guide_axis(angle = 45)) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  scale_fill_manual(values = c("#E69F00", "#0072B2", "#009E73")) + # supplies, consumption, purchases
  theme(legend.title = element_blank()) 
  #theme(legend.position = "none")


df_UK_seafoodDB_PCW_sum$Commodity_f <-  factor(df_UK_seafoodDB_PCW_sum$Commodity, levels = c("Supply", "Purchases", "Consumption"))

# Plot total seafood supplied, purchases and consumed (g/capita/week) between 2009 and 2018. 
ggplot(df_UK_seafoodDB_PCW_sum, aes(Year, Volume, fill= Commodity_f)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_y_continuous(name = "Amount of seafood (g/capita/week)", limits = c(0,300)) +
  scale_x_continuous(name = "Year", breaks = seq(2009, 2018, 1), 
                     guide = guide_axis(angle = 45)) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  scale_fill_manual(values = c("#009E73", "#0072B2", "#E69F00")) + # supplies, consumption, purchases
  theme(legend.title = element_blank()) 
  #theme(legend.position = "none")


```


```{r Seafood waste estimates}
# Calculate seafood waste
df_UK_seafoodDB_PCW_short$Waste <- df_UK_seafoodDB_PCW_short$Purchases - df_UK_seafoodDB_PCW_short$Consumption

# Aggregate data 
df_UK_seafoodWaste <- aggregate(Waste ~ Year, data = df_UK_seafoodDB_PCW_short, sum)

ggplot(df_UK_seafoodWaste, aes(Year, Waste)) +
  geom_bar(position = "stack", stat= "identity", color = "black") +
  scale_y_continuous(name = "Seafood waste(g/capita/week)", limits = c(0,300)) +
  scale_x_continuous(name = "Year", breaks = seq(2009, 2018, 1), 
                     guide = guide_axis(angle = 45)) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  scale_fill_manual(values = "#CC79A7") + 
  theme(legend.title = element_blank()) 

```



### Figure 3. Total UK domestic UK seafood production (g/capita/week), bu species type between 2009 and 2018.

```{r Domestic seafood production}
# Subset production commodity 
df_UK_seafoodProduction_PCW <- df_UK_seafoodDB_PCW_short[c("Production", "Year", "Species", "SACN")]

# Sum UK seafood production, per SACN
df_UK_seafoodProduction_SACN <- aggregate(Production ~ SACN + Year, data = df_UK_seafoodProduction_PCW, sum)

# Select for lean and oily fish only
# Include "other" seafood types e.g. cephalopods and unknowns? 
df_UK_seafoodProduction_LOS <- subset(df_UK_seafoodProduction_SACN, SACN == "Lean" | SACN == "Oily" | SACN == "Shellfish")

df_UK_seafoodProduction_LOSO <- subset(df_UK_seafoodProduction_SACN, SACN == "Lean" | SACN == "Oily" | SACN == "Shellfish" 
                                        | SACN == "Other" )

# State order of the seafood types
df_UK_seafoodProduction_LOS$SACN_f <-  factor(df_UK_seafoodProduction_LOS$SACN, levels = c("Shellfish", "Lean", "Oily"))

df_UK_seafoodProduction_LOSO$SACN_f <-  factor(df_UK_seafoodProduction_LOSO$SACN, levels = c("Other", "Shellfish", 
                                                                                             "Lean", "Oily"))


# Plot average seafood supply (g/capita/week), to SACN level (lean and oily) between 2009 and 2018. 
ggplot(df_UK_seafoodProduction_LOSO, aes(y = Production, x = Year, fill = SACN_f)) +
  geom_bar(position = "stack", stat = "identity", color = "black", width = 0.5) + 
  scale_y_continuous(name = "Total seafood production (g/capita/week)") +
  scale_x_continuous(name = "Year", breaks = seq(2009, 2018, 1), 
                     guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#999999", "#DDCC77",  "#CC79A7","#D55E00")) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2.0) + 
  theme(legend.title = element_blank())

```



### Figure 5. Nutrients supplied and exported per species in 2018. 

To include calcium, iron, vitamin D, vitamin A, vitamin B12, iodine, selenium, and zinc

```{r Calcualte nutrient supplies and exports in PCW}
# Calculate supplies 
df_UK_seafoodDBNC$Supply <- (df_UK_seafoodDBNC$Production + 
                               df_UK_seafoodDBNC$Imports)- df_UK_seafoodDBNC$Exports

# Divide nutrients by 100g and multiply nutrient content by supplies
df_UK_seafoodDBNC$SupplyPUFA_g <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$TotalPUFA_g100g/ 100)

df_UK_seafoodDBNC$SupplyVitaminA_ug <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$VitaminA_µg100g/ 100)

df_UK_seafoodDBNC$SupplyVitaminD_ug <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$VitaminD_µg100g/ 100)

df_UK_seafoodDBNC$SupplyVitaminB12_ug <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$VitaminB12_µg100g/ 100)

df_UK_seafoodDBNC$SupplyZinc_mg <- df_UK_seafoodDBNC$Supply * 
  (df_UK_seafoodDBNC$Zinc_mg100g/ 100)

df_UK_seafoodDBNC$SupplyIron_mg <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$Iron_mg100g/ 100)

df_UK_seafoodDBNC$SupplyCalcium_mg <- df_UK_seafoodDBNC$Supply *
  (df_UK_seafoodDBNC$Calcium_mg100g/ 100)

df_UK_seafoodDBNC$SupplySelenium_ug <- df_UK_seafoodDBNC$Supply * 
  (df_UK_seafoodDBNC$Selenium_µg100g/ 100)

df_UK_seafoodDBNC$SupplyIodine_ug <- df_UK_seafoodDBNC$Supply * 
  (df_UK_seafoodDBNC$Iodine_µg100g/ 100)


# Divide nutrients by 100g and multiply nutrient content by exports
df_UK_seafoodDBNC$ExportsPUFA_g <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$TotalPUFA_g100g/ 100)

df_UK_seafoodDBNC$ExportsVitaminA_ug <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$VitaminA_µg100g/ 100)

df_UK_seafoodDBNC$ExportsVitaminD_ug <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$VitaminD_µg100g/ 100)

df_UK_seafoodDBNC$ExportsVitaminB12_ug <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$VitaminB12_µg100g/ 100)

df_UK_seafoodDBNC$ExportsZinc_mg <- df_UK_seafoodDBNC$Exports * 
  (df_UK_seafoodDBNC$Zinc_mg100g/ 100)

df_UK_seafoodDBNC$ExportsIron_mg <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$Iron_mg100g/ 100)

df_UK_seafoodDBNC$ExportsCalcium_mg <- df_UK_seafoodDBNC$Exports *
  (df_UK_seafoodDBNC$Calcium_mg100g/ 100)

df_UK_seafoodDBNC$ExportsSelenium_ug <- df_UK_seafoodDBNC$Exports * 
  (df_UK_seafoodDBNC$Selenium_µg100g/ 100)

df_UK_seafoodDBNC$ExportsIodine_ug <- df_UK_seafoodDBNC$Exports * 
  (df_UK_seafoodDBNC$Iodine_µg100g/ 100)


# Divide nutrient commodities by population size, and 52 to get to g/capita/day
df_UK_seafoodDBNC$SupplyPUFA_gPCW <- (df_UK_seafoodDBNC$SupplyPUFA_g/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyVitaminA_ugPCW <- (df_UK_seafoodDBNC$SupplyVitaminA_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyVitaminD_ugPCW <- (df_UK_seafoodDBNC$SupplyVitaminD_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyVitaminB12_ugPCW <- (df_UK_seafoodDBNC$SupplyVitaminB12_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyIron_mgPCW <- (df_UK_seafoodDBNC$SupplyIron_mg/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyCalcium_mgPCW <- (df_UK_seafoodDBNC$SupplyCalcium_mg/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplySelenium_ugPCW <- (df_UK_seafoodDBNC$SupplySelenium_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$SupplyIodine_ugPCW <- (df_UK_seafoodDBNC$SupplyIodine_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52


# Exports
df_UK_seafoodDBNC$ExportsPUFA_gPCW <- (df_UK_seafoodDBNC$ExportsPUFA_g/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsVitaminA_ugPCW <- (df_UK_seafoodDBNC$ExportsVitaminA_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsVitaminD_ugPCW <- (df_UK_seafoodDBNC$ExportsVitaminD_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsVitaminB12_ugPCW <- (df_UK_seafoodDBNC$ExportsVitaminB12_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsIron_mgPCW <- (df_UK_seafoodDBNC$ExportsIron_mg/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsCalcium_mgPCW <- (df_UK_seafoodDBNC$ExportsCalcium_mg/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsSelenium_ugPCW <- (df_UK_seafoodDBNC$ExportsSelenium_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52
df_UK_seafoodDBNC$ExportsIodine_ugPCW <- (df_UK_seafoodDBNC$ExportsIodine_ug/
                                   df_UK_seafoodDBNC$UKPOP) / 52



# Convert to same nutrients (mg)
#df_UK_seafoodDBNC$SupplyVitaminA_mgPCW <- df_UK_seafoodDBNC$SupplyVitaminA_ugPCW / 1000
#df_UK_seafoodDBNC$SupplyVitaminD_mgPCW <- df_UK_seafoodDBNC$SupplyVitaminD_ugPCW / 1000
#df_UK_seafoodDBNC$SupplyVitaminB12_mgPCW <- df_UK_seafoodDBNC$SupplyVitaminB12_ugPCW / 1000
#df_UK_seafoodDBNC$SupplySelenium_mgPCW <- df_UK_seafoodDBNC$SupplySelenium_ugPCW / 1000
#df_UK_seafoodDBNC$SupplyIodine_mgPCW <- df_UK_seafoodDBNC$SupplyIodine_ugPCW / 1000


#df_UK_seafoodDBNC$ExportsVitaminA_mgPCW <- df_UK_seafoodDBNC$ExportsVitaminA_ugPCW / 1000
#df_UK_seafoodDBNC$ExportsVitaminD_mgPCW <- df_UK_seafoodDBNC$ExportsVitaminD_ugPCW / 1000
#df_UK_seafoodDBNC$ExportsVitaminB12_mgPCW <- df_UK_seafoodDBNC$ExportsVitaminB12_ugPCW / 1000
#df_UK_seafoodDBNC$ExportsSelenium_mgPCW <- df_UK_seafoodDBNC$ExportsSelenium_ugPCW / 1000
#df_UK_seafoodDBNC$ExportsIodine_mgPCW <- df_UK_seafoodDBNC$ExportsIodine_ugPCW / 1000


# Convert to same nutrients (ug)
df_UK_seafoodDBNC$SupplyPUFA_ugPCW <- df_UK_seafoodDBNC$SupplyPUFA_gPCW * 1000000
df_UK_seafoodDBNC$SupplyIron_ugPCW <- df_UK_seafoodDBNC$SupplyIron_mgPCW * 1000
df_UK_seafoodDBNC$SupplyCalcium_ugPCW <- df_UK_seafoodDBNC$SupplyCalcium_mgPCW * 1000

df_UK_seafoodDBNC$ExportsPUFA_ugPCW <- df_UK_seafoodDBNC$ExportsPUFA_gPCW * 1000000
df_UK_seafoodDBNC$ExportsIron_ugPCW <- df_UK_seafoodDBNC$ExportsIron_mgPCW * 1000
df_UK_seafoodDBNC$ExportsCalcium_ugPCW <- df_UK_seafoodDBNC$ExportsCalcium_mgPCW * 1000


# Subset for 2018 only (most recent)
df_UK_seafoodDBNC_2018 <- subset(df_UK_seafoodDBNC, Year == 2018)
unique(df_UK_seafoodDBNC_2018$Year)

# Subset supply
df_nutrientSupply_ug <- df_UK_seafoodDBNC_2018 %>% select(Species, Year, SACN,
                                                  SupplyPUFA_ugPCW,SupplyVitaminA_ugPCW, 
                                         SupplyVitaminD_ugPCW, SupplyVitaminB12_ugPCW,
                                         SupplyIron_ugPCW, SupplyCalcium_ugPCW,   
                                         SupplySelenium_ugPCW, SupplyIodine_ugPCW)
                                         
# Subset exports
df_nutrientExports_ug <- df_UK_seafoodDBNC_2018 %>% select(Species, Year, SACN,
                                                   ExportsPUFA_ugPCW,ExportsVitaminA_ugPCW,
                                         ExportsVitaminD_ugPCW, ExportsVitaminB12_ugPCW,
                                         ExportsIron_ugPCW, ExportsCalcium_ugPCW,
                                         ExportsSelenium_ugPCW, ExportsIodine_ugPCW)

# Restructure data set
df_nutrientSupply_ug_values <- melt(df_nutrientSupply_ug, id.vars = c("Year", "Species", "SACN"), variable.name = "Nutrient", value.name = "Volume")

df_nutrientExports_ug_values <- melt(df_nutrientExports_ug, id.vars = c("Year", "Species", "SACN"), variable.name = "Nutrient", value.name = "Volume")

df_nutrientSupply_ug_values$Volume_10000 <- df_nutrientSupply_ug_values$Volume * 10000
df_nutrientExports_ug_values$Volume_10000 <- df_nutrientExports_ug_values$Volume * 10000

# Only include nutrients if volume is greater than 0.
df_nutrientSupply_ug_10000<- subset(df_nutrientSupply_ug_values, Volume_10000 > 0)
df_nutrientExports_ug_10000 <- subset(df_nutrientExports_ug_values, Volume_10000 > 0)
```


```{r Calcualte nutrients supplied (capita/week) in 2018}
# Log scale
ggplot(df_nutrientSupply_ug_10000, aes(Species, Volume_10000, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#AA4499", "#44AA99", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00")) +
  theme(legend.title = element_blank()) +
  facet_grid(.~SACN, scales = "free_x", space = "free_x") +
  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 90000, 10000), 
                           seq(100000, 1000000, 100000)), 
                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1 µg","",
                           "","","","","","","","10 µg","","","","","","","","","100 µg","","","","","",
                           "","","","1 mg","","","","","","","","","10 mg","","","","","","","","",
                           "100 mg","","","","","","","","","1 g")) +
  theme(legend.title = element_blank(), 
        strip.background = element_rect(fill= c("#D55E00","#999999", "#DDCC77", "#CC79A7")))

#theme(legend.position = "none")
# Ask BS about strip.background element color fill- can you include more than one color?
```


```{r Calcualte nutrients exported (capita/week) in 2018}
# Plot amount of nutrients exported (capita/week) in 2018
# Log scale
ggplot(df_nutrientExports_ug_10000, aes(Species, Volume_10000, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#AA4499", "#44AA99", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00")) +
  theme(legend.title = element_blank()) +
  facet_grid(.~SACN, scales = "free_x", space = "free_x") +
  theme(legend.position = "none", strip.background = element_rect(fill= c("#999999", "#DDCC77", "#CC79A7","#D55E00"))) +
  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 90000, 10000), 
                           seq(100000, 1000000, 100000)), 
                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1 µg","",
                           "","","","","","","","10 µg","","","","","","","","","100 µg","","","","","",
                           "","","","1 mg","","","","","","","","","10 mg","","","","","","","","",
                           "100 mg","","","","","","","","","1 g"))

```

