---
title: "Untitled"
author: "AL"
date: "2023-05-15"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Preparation 

```{r Load libraries, include = FALSE}
# Load packages
library(tidyr) # for tidying data
library(dplyr) # base R alternative but neater
library(vroom) # for loading and transforming data
library(tidyverse) # data exploration 
library(reshape2) # for melting data frames i.e. short and wide to long and thin
library(data.table) # for fread()-function
library(mice) # md.pattern to show missing data
library(plyr) # joins multiple data frames together
library(ggplot2) # makes plots fancier
library(scales) # displays integers on the axis
library(ggthemes) # contains extra themes, scales and functions for and related to ggplot2
library(gridExtra)
library(cowplot) # Plots two figures one output

```


```{r Edit chunk settings, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warninf = FALSE, 
  fig.height = 9, 
  fig.width = 16
)
```


```{r Setup default for figures, include=FALSE}
# Set default presentation of figures
theme_set(theme_bw()%+replace%
            theme(
              title = element_text(size = 26), 
              text = element_text(size = 30), 
              axis.text = element_text(size = 26, colour = "gray40"), # increase to make readable
              legend.key.size = unit(1.2, "cm"), 
              legend.title = element_text(size = 26), 
              legend.text = element_text(size = 24),
              panel.grid.major = element_line(colour= "gray40", linetype = "dotted", linewidth = 0.9), 
              panel.grid.minor = element_line(colour = "gray70", linetype = "dotted", linewidth = 0.7)
            ))
# instead of "size" can also use "linewidth"
```


```{r Set colour-blind palette}
# Colour-blind friendly palette with grey. Try to keep the order (http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette)
cbPalette <- c( "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")
#consumption, exports, imports, production, purchases, supplies

```


```{r Set colour-blind palette}
# Colours will be allocated in commodity alphabetical order. 
```


```{r Load file path, echo=TRUE}
# Loading file path to the data into a value 
source("Data_filepath.R")# Data_filepath.R is listed in .gitignore-file. So, you will need to create that file yourself and provide your respected filepath using "data_dir <- [enter your here]"
```

```{r Specify the desired file path}
filepath <- paste(data_dir,"Outputs", sep = "") 
# note we are able to change this to another file e.g. saving the output
```

```{r Load the seafood database}
# Load database 
df_UK_seafoodDB_PCW <- vroom(file=paste(filepath,"Seafood-database-PCW_preliminary.csv", sep="/"), na = c("NA"))
```


```{r Specify the desired file path}
filepath <- paste(data_dir,"Outputs", sep = "") 
# note we are able to change this to another file e.g. saving the output
```


```{r Load the database}
# Load database 
df_UK_seafoodDB <- vroom(file=paste(filepath,"Seafood-database_preliminary.csv", sep="/"), na = c("NA"))

# Convert NA to 0
df_UK_seafoodDB[is.na(df_UK_seafoodDB)] <- 0

# Check the structure 
str(df_UK_seafoodDB)

# Simplify data set and select desired columns 
df_UK_seafoodDB_simp <- df_UK_seafoodDB[c("Species", "SpeciesType", "SACN", "Year", "Commodity", 
                                                    "Volume" )]
str(df_UK_seafoodDB_simp)

# Make data frame wide and short
df_UK_seafoodDB_short <- df_UK_seafoodDB_simp %>%
  pivot_wider(names_from = Commodity, values_from = Volume)
unique(df_UK_seafoodDB_simp$Volume)
range(df_UK_seafoodDB_simp$Volume)

str(df_UK_seafoodDB_short)

```



### Figure. Total UK seafood supplied and consummed (g/capita/week) between 2009 and 2018  


```{r Total UK seafood supplied and consumed (g/capita/week) between 2009 and 2018}
# Sum annual seafood supplies per capita 
df_UK_supplies_tot <- aggregate(Supplies_pcw ~ Year, data = df_seafoodDB_pop_short, sum)
df_UK_consummed_tot <- aggregate(Consumption_pcw ~ Year, data = df_seafoodDB_pop_short, sum)

str(df_UK_supplies_tot)
str(df_UK_consummed_tot)

# Rename data frame variables 
names(df_UK_supplies_tot) <- c("Year", "Value")
names(df_UK_consummed_tot) <- c("Year", "Value")

# Add additional variable
df_UK_supplies_tot$Commodity <- "Supplies"
df_UK_consummed_tot$Commodity <- "Consumption"

# rbind data frames
df_UK_supplies_intake_tot<- rbind(df_UK_supplies_tot, df_UK_consummed_tot)

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
ggplot(df_UK_supplies_intake_tot, aes(Year, Value, fill= Commodity)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_y_continuous(name = "Amount of seafood (g/capita/week)", limits = c(0,300)) +
  scale_x_continuous(name = "Year", breaks = seq(2009, 2018, 1), 
                     guide = guide_axis(angle = 45)) +
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  geom_hline(yintercept = 140, linetype = "twodash", color = "navyblue", linewidth = 2) +
  scale_fill_manual(values = c("#E69F00", "#009E73")) +
  theme(legend.title = element_blank()) 

```



```{r Seafood supplies by fish type for 2018}
# Subset production commodity 
str(df_UK_seafoodDB_nutComp)

df_UK_seafoodSuppliesSimp <- df_seafoodDB_pop_short[c("Supplies_pcw", "Year", "Species", "SpeciesType", "SACN", "UKPOP")]

# Calculate UK production per capita
#df_UK_seafoodProduction$ProductionCapita <- df_UK_seafoodProduction$Production / df_UK_seafoodProduction$UKPOP
#df_UK_seafoodProduction$ProductionCapitaWeek <- df_UK_seafoodProduction$ProductionCapita / 7

# Subset data for 2018
#df_UK_SFProductionCapita_18 <- subset(df_UK_seafoodProduction, Year == "2018")

# Sum UK seafood production, per SACN
df_UK_Supplies_sum_SACN <- aggregate(Supplies_pcw ~ SACN + Year, data = df_UK_seafoodSuppliesSimp, sum)

df_UK_Supplies_avg_10_SACN <- aggregate(Supplies_pcw ~ SACN, data = df_UK_Supplies_sum_SACN, mean)
df_UK_Supplies_avg_10_SACN$FishType <- "Fish type"

# Select for lean and oily fish only
#df_UK_production_2018 <- subset(df_UK_SFProduction_cap_2018_SACN, SACN == "Lean" | SACN == "Oily")

unique(df_UK_Supplies_avg_10_SACN$SACN)

df_UK_Supplies_avg_10_SACN$SACN_f <-  factor(df_UK_Supplies_avg_10_SACN$SACN, levels = c("NoData", "Shellfish", "Lean", "Oily"))

# Convert variable to factor to specify order
#df_UK_supplies_SACN_avg_LOS$SACN <- factor(df_UK_supplies_SACN_avg_LOS$SACN, levels = c("Shellfish", "Lean", "Oily"))

  
#df_UK_supplies_nutrients_values$SACN_f <- factor(df_UK_supplies_nutrients_values$SACN, levels = c("Oily", "Lean", "Shellfish"))

# Plot average seafood supply (g/capita/week), to SACN level (lean and oily) between 2009 and 2018. 
ggplot(df_UK_Supplies_avg_10_SACN, aes(y = Supplies_pcw, x = FishType, fill = SACN_f)) +
  geom_bar(position = "stack", stat = "identity", color = "black", width = 0.5) + 
  scale_y_continuous(name = "", limits = c(0,300)) +
  scale_x_discrete(name = "") +
  scale_fill_manual(values = c("#DDCC77","#999999", "#CC79A7","#D55E00"))+
  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
  geom_hline(yintercept = 140, linetype = "twodash", color = "navyblue", linewidth = 2)



```





### Figure 3


```{r Load the seafood database}
# Load database 
df_UK_seafoodDB_nutComp <- vroom(file=paste(filepath,"Seafood-database-PCW_NutCOMP_preliminary.csv", sep="/"), na = c("NA"))

str(df_UK_seafoodDB_nutComp)
```


```{r Seafood production, imports and exports by nutrient}
# Subset 2018 data only
df_UK_seafoodDB_nutComp_2018_all <- subset(df_UK_seafoodDB_nutComp, Year == 2018)

# Check ranges selected 
range(df_UK_seafoodDB_nutComp_2018_all$Year)

# Select species with positive supplies only
df_UK_seafoodDB_nutComp_2018 <- subset(df_UK_seafoodDB_nutComp_2018_all, Supplies > 0 & VitaminD_µg > 0 & TotalPUFA_g > 0)

range(df_UK_seafoodDB_nutComp_2018$Supplies)
range(df_seafoodDB_pop_short$Supplies)
str(df_UK_seafoodDB_nutComp_2018_all)

# Production
df_UK_seafoodDB_nutComp_2018$TotalPUFAProd_g <- (df_UK_seafoodDB_nutComp_2018$Production * df_UK_seafoodDB_nutComp_2018$TotalPUFA_g)/100
df_UK_seafoodDB_nutComp_2018$VitDProd_ug <- (df_UK_seafoodDB_nutComp_2018$Production * df_UK_seafoodDB_nutComp_2018$VitaminD_µg)/100
#df_UK_seafoodDB_nutComp_2018$VitDProd_g <- df_UK_seafoodDB_nutComp_2018$VitDProd_ug / 1000000

# Imports
df_UK_seafoodDB_nutComp_2018$TotalPUFAImports_g <- (df_UK_seafoodDB_nutComp_2018$Imports * df_UK_seafoodDB_nutComp_2018$TotalPUFA_g)/100
df_UK_seafoodDB_nutComp_2018$VitDImports_ug <- (df_UK_seafoodDB_nutComp_2018$Imports * df_UK_seafoodDB_nutComp_2018$VitaminD_µg)/100
#df_UK_seafoodDB_nutComp_2018$VitDImports_g <- df_UK_seafoodDB_nutComp_2018$VitDImports_ug / 1000000


# Exports
df_UK_seafoodDB_nutComp_2018$TotalPUFAExports_g <- (df_UK_seafoodDB_nutComp_2018$Exports * df_UK_seafoodDB_nutComp_2018$TotalPUFA_g)/100
df_UK_seafoodDB_nutComp_2018$VitDExports_ug <- (df_UK_seafoodDB_nutComp_2018$Exports * df_UK_seafoodDB_nutComp_2018$VitaminD_µg)/100
#df_UK_seafoodDB_nutComp_2018$VitDExports_g <-df_UK_seafoodDB_nutComp_2018$VitDExports_ug / 1000000


str(df_UK_seafoodDB_nutComp_2018)

# Calculate  availability 
# PUFA supplies
df_UK_seafoodDB_nutComp_2018$PUFASupplies_g <-
  (df_UK_seafoodDB_nutComp_2018$TotalPUFAProd_g +
                                          df_UK_seafoodDB_nutComp_2018$TotalPUFAImports_g) -
  df_UK_seafoodDB_nutComp_2018$TotalPUFAExports_g

# Vitamin D supplies g
#df_UK_seafoodDB_nutComp_2018$VitDSupplies_g <- (df_UK_seafoodDB_nutComp_2018$VitDProd_g +
#                                          df_UK_seafoodDB_nutComp_2018$VitDImports_g)-
#  df_UK_seafoodDB_nutComp_2018$VitDExports_g


# Vitamin D supplies ug
df_UK_seafoodDB_nutComp_2018$VitDSupplies_ug <- (df_UK_seafoodDB_nutComp_2018$VitDProd_ug +
                                          df_UK_seafoodDB_nutComp_2018$VitDImports_ug)-
  df_UK_seafoodDB_nutComp_2018$VitDExports_ug

```

```{r Total nutrients produced and imported}
# Sum UK seafood production, per SACN
#df_UK_pos_PUFA_SACN <- aggregate(PosPUFASupplies_g ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)

#str(df_UK_pos_PUFA_SACN)

#df_UK_pos_vitD_SACN <- aggregate(PosVitDSupplies_g ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)

#str(df_UK_pos_vitD_SACN)

```


```{r Convert to g/capita/day}
# Add in UK population size column 
#df_UK_pos_PUFA_SACN$Pop <- 66435600
#df_UK_pos_vitD_SACN$Pop <- 66435600

# Divide nutrient commodities by population size, and 365 to get to g/capita/day
#df_UK_pos_PUFA_SACN$PCD <- (df_UK_pos_PUFA_SACN$PosPUFASupplies_g/ df_UK_pos_PUFA_SACN$Pop) / 365
#df_UK_pos_vitD_SACN$PCD <- (df_UK_pos_vitD_SACN$PosVitDSupplies_g/ df_UK_pos_vitD_SACN$Pop) / 365

```


```{r Convert to g/capita/day}
# Sum annual seafood supplies per capita 
#df_UK_pos_PUFA <- aggregate(Supplies_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)
#df_UK_pos_vitD <- aggregate(Consumpiton_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)

# Rename data frame variables 
#names(df_UK_pos_PUFA_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")
#names(df_UK_pos_vitD_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")

# Add additional variable
#df_UK_pos_PUFA_SACN$Nutrient <- "Total_PUFA"
#df_UK_pos_vitD_SACN$Nutrient <- "Vitamin_D"

# rbind data frames
#df_UK_pos_nutrients <- rbind(df_UK_pos_PUFA_SACN, df_UK_pos_vitD_SACN)
#range(df_UK_pos_nutrients$Volume)


# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
#ggplot(df_UK_pos_nutrients, aes(Species, PCD, fill= Nutrient)) +
#  geom_bar(position = "dodge", stat= "identity", color = "black") +
#  scale_y_continuous(name = "Amount of nutrient (g/capita/day)", limits = c(0, 0.5)) +
#  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
#  geom_hline(yintercept = 280, linetype = "dashed", color = "red", linewidth = 2) +
#  geom_hline(yintercept = 140, linetype = "twodash", color = "navyblue", linewidth = 2) +
#  scale_fill_manual(values = c("#E69F00", "#009E73")) +
#  theme(legend.title = element_blank()) +
#  facet_wrap(~SACN, scales = "free")


```



```{r Nutrients exported}
# Sum UK seafood production, per SACN
df_UK_neg_PUFA_SACN <- aggregate(TotalPUFAExports_g ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)
df_UK_neg_vitD_SACN <- aggregate(VitDExports_ug ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)

```


```{r Convert to g/capita/day}
# Add in UK population size column 
df_UK_neg_PUFA_SACN$Pop <- 66435600
df_UK_neg_vitD_SACN$Pop <- 66435600

# Divide nutrient commodities by population size, and 365 to get to g/capita/day
#df_UK_neg_PUFA_SACN$PCD <- (df_UK_neg_PUFA_SACN$TotalPUFAExports_g/ df_UK_neg_PUFA_SACN$Pop) / 365
#df_UK_neg_vitD_SACN$PCD <- (df_UK_neg_vitD_SACN$VitDExports_g/ df_UK_neg_vitD_SACN$Pop) / 365

df_UK_neg_PUFA_SACN$PCW_g <- (df_UK_neg_PUFA_SACN$TotalPUFAExports_g/ df_UK_neg_PUFA_SACN$Pop) / 52

#df_UK_neg_vitD_SACN$PCW_g <- (df_UK_neg_vitD_SACN$VitDExports_g/ df_UK_neg_vitD_SACN$Pop) / 52
df_UK_neg_vitD_SACN$PCW_ug <- (df_UK_neg_vitD_SACN$VitDExports_ug/ df_UK_neg_vitD_SACN$Pop) / 52
```


```{r Convert to g/capita/day}
# Sum annual seafood supplies per capita 
#df_UK_neg_PUFA_SACN <- aggregate(Supplies_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)
#df_UK_neg_vitD_SACN <- aggregate(Consumpiton_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)

str(df_UK_neg_vitD_SACN)

# Rename data frame variables 
names(df_UK_neg_PUFA_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCW")
names(df_UK_neg_vitD_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCW")

# Add additional variable
df_UK_neg_PUFA_SACN$Nutrient <- "Total PUFA"
df_UK_neg_vitD_SACN$Nutrient <- "Vitamin D"

# rbind data frames
df_UK_neg_nutrients <- rbind(df_UK_neg_PUFA_SACN, df_UK_neg_vitD_SACN)

# Continous scale

#df_UK_neg_nutrients_LS <- subset(df_UK_neg_nutrients, SACN == "Lean" | SACN == "Shellfish")

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
#ggplot(df_UK_neg_nutrients, aes(Species, PCW, fill= Nutrient)) +
#  geom_bar(position = "dodge", stat= "identity", color = "black") +
#  scale_y_continuous(name = "Amount of nutrient (g/capita/day)", limits = c(0, 0.013)) +
#  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  #geom_hline(yintercept = 250, linetype = "dashed", color = "#E69F00", linewidth = 2) +
  #geom_hline(yintercept = 10, linetype = "twodash", color = "#009E73", linewidth = 2) +
#  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
#  theme(legend.title = element_blank()) +
#  facet_wrap(~SACN, scales = "free_x") +
#  theme(legend.position = "none", strip.background = element_rect(fill= c("#CC79A7", "#999999")),
#  strip.text=element_text(color="black"))


#df_UK_neg_nutrients_O <- subset(df_UK_neg_nutrients, SACN == "Oily")

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
#ggplot(df_UK_neg_nutrients, aes(Species, PCD, fill= Nutrient)) +
#  geom_bar(position = "dodge", stat= "identity", color = "black") +
#  scale_y_continuous(name = "", limits = c(0, 0.3)) +
#  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  #geom_hline(yintercept = 250, linetype = "dashed", color = "#E69F00", linewidth = 2) +
  #geom_hline(yintercept = 10, linetype = "twodash", color = "#009E73", linewidth = 2) +
#  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
#  theme(legend.title = element_blank()) 

+
#  facet_wrap(~SACN, scales = "free_x") +
#  theme(legend.position = "none", strip.background = element_rect(fill="#D55E00"), 
#  strip.text=element_text(color="black")) 

# Group by fish type? 
# vit D DRV: 10 ug fish inake
# omega-3: 250 ug 

```




```{r}
# Sum UK seafood production, per SACN
df_UK_supplies_PUFA_SACN <- aggregate(PUFASupplies_g ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)

str(df_UK_supplies_PUFA_SACN)

df_UK_supplies_vitD_SACN <- aggregate(VitDSupplies_ug ~ SACN + Species, data = df_UK_seafoodDB_nutComp_2018, sum)

str(df_UK_supplies_vitD_SACN)

```


```{r Convert to g/capita/day}
# Add in UK population size column 
df_UK_supplies_PUFA_SACN$Pop <- 66435600
df_UK_supplies_vitD_SACN$Pop <- 66435600

# Divide nutrient commodities by popualtion size, and 365 to get to g/capita/day
df_UK_supplies_PUFA_SACN$PCW <- (df_UK_supplies_PUFA_SACN$PUFASupplies_g/ df_UK_supplies_PUFA_SACN$Pop) / 52
df_UK_supplies_vitD_SACN$PCW <- (df_UK_supplies_vitD_SACN$VitDSupplies_ug/ df_UK_supplies_vitD_SACN$Pop) / 52

str(df_UK_supplies_vitD_SACN)

```



```{r Convert to g/capita/day}
# Sum annual seafood supplies per capita 
#df_UK_pos_PUFA <- aggregate(Supplies_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)
#df_UK_pos_vitD <- aggregate(Consumpiton_pcw ~ Year, data = df_UK_seafoodDB_PCW, sum)

# Rename data frame variables 
names(df_UK_supplies_PUFA_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCW")
names(df_UK_supplies_vitD_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCW")

# Add additional variable
df_UK_supplies_PUFA_SACN$Nutrient <- "Total_PUFA"
df_UK_supplies_vitD_SACN$Nutrient <- "Vitamin_D"

# rbind data frames
df_UK_supplies_nutrients <- rbind(df_UK_supplies_PUFA_SACN, df_UK_supplies_vitD_SACN)

#df_UK_neg_nutrients_LS <- subset(df_UK_neg_nutrients, SACN == "Lean" | SACN == "Shellfish")

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
ggplot(df_UK_supplies_nutrients, aes(Species, PCW, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_y_continuous(name = "Amount of nutrient (g/capita/day)", limits = c(0, 0.005)) + # axis bounds set differently
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  #geom_hline(yintercept = 250, linetype = "dashed", color = "#E69F00", linewidth = 2) +
  #geom_hline(yintercept = 10, linetype = "twodash", color = "#009E73", linewidth = 2) +
  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
  theme(legend.title = element_blank()) +
  facet_wrap(~SACN, scales = "free_x") +
  theme(legend.position = "none", strip.background = element_rect(fill= c("#CC79A7", "#999999")),
  strip.text=element_text(color="black"))

#df_UK_neg_nutrients_O <- subset(df_UK_neg_nutrients, SACN == "Oily")

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
ggplot(df_UK_supplies_nutrients, aes(Species, PCW, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_y_continuous(name = "", limits = c(0, 0.3)) +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  #geom_hline(yintercept = 250, linetype = "dashed", color = "#E69F00", linewidth = 2) +
  #geom_hline(yintercept = 10, linetype = "twodash", color = "#009E73", linewidth = 2) +
  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
  theme(legend.title = element_blank()) +
  facet_wrap(~SACN, scales = "free_x") +
  theme(legend.position = "none", strip.background = element_rect(fill="#D55E00"), 
  strip.text=element_text(color="black")) 

# Group by fish type? 
# vit D DRV: 10 ug fish inake
# omega-3: 250 ug
```


```{r Log scale: nutrient supplies}
# Check structure
#str(df_UK_supplies_vitD_SACN)

# Rename data frame variables 
#names(df_UK_supplies_PUFA_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")
#names(df_UK_supplies_vitD_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")

# Add additional variable
#df_UK_supplies_PUFA_SACN$Nutrient <- "Total_PUFA"
#df_UK_supplies_vitD_SACN$Nutrient <- "Vitamin_D"

# rbind data frames
#df_UK_supplied_nutrients <- rbind(df_UK_supplies_PUFA_SACN, df_UK_supplies_vitD_SACN)

# Multipy value by 100000

# Plot total seafood supplied and consumed (g/capita/week) between 2009 and 2018. 
#ggplot(df_UK_supplies_nutrients, aes(Species, PCW_1000000, fill= Nutrient)) +
#  geom_bar(position = "dodge", stat= "identity", color = "black") +
#  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
#  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
#  theme(legend.title = element_blank()) +
#  facet_wrap(~SACN, scales = "free_x") +
#  theme(legend.position = "none") +
#  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
#                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 100000, 10000)), 
#                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1","",
#                           "","","","","","","","10","","","","","","","","","100","","","","","",
#                           "","","","1000","","","","","","","","","10000","" ,"","","","","","","","100000"))

df_UK_supplies_nutrients$PCW_10000 <- df_UK_supplies_nutrients$PCW * 10000

df_UK_supplies_nutrients_values <- subset(df_UK_supplies_nutrients, PCW_10000 > 1)


df_UK_supplies_nutrients_values$SACN_f <- factor(df_UK_supplies_nutrients_values$SACN, levels = c("Oily", "Lean", "Shellfish"))

ggplot(df_UK_supplies_nutrients_values, aes(Species, PCW_10000, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
  theme(legend.title = element_blank()) +
  facet_grid(.~SACN_f, scales = "free_x", space = "free_x") +
  theme(legend.position = "none") +
  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 90000, 10000), seq(1000000, 10000000, 1000000)), 
                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1 µg","",
                           "","","","","","","","10 µg","","","","","","","","","100 µg","","","","","",
                           "","","","1 mg","","","","","","","","","10 mg","11 mg","","","","","","","","100 g","","","","","","","","","1 kg"))

```



```{r Log scale: negative nutrient supplies}
# Check structure
#str(df_UK_supplies_vitD_SACN)

# Rename data frame variables 
#names(df_UK_supplies_PUFA_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")
#names(df_UK_supplies_vitD_SACN) <- c("SACN", "Species", "Volume", "Pop", "PCD")

# Add additional variable
#df_UK_supplies_PUFA_SACN$Nutrient <- "Total_PUFA"
#f_UK_supplies_vitD_SACN$Nutrient <- "Vitamin_D"

# rbind data frames
#df_UK_supplied_nutrients <- rbind(df_UK_supplies_PUFA_SACN, df_UK_supplies_vitD_SACN)


str(df_UK_neg_vitD_SACN)
# Multipy value by 100000
#df_UK_neg_nutrients$PCW_1000000 <- df_UK_neg_nutrients$PCW * 1000000
#range(df_UK_neg_nutrients$PCW_1000000)

df_UK_neg_nutrients$PCW_10000 <- df_UK_neg_nutrients$PCW * 10000 # can't go smaller
#df_UK_neg_nutrients$PCW_1000 <- df_UK_neg_nutrients$PCW * 1000

df_UK_neg_nutrients_values <- subset(df_UK_neg_nutrients, PCW_10000 > 0)
#df_UK_neg_nutrients_values_1000 <- subset(df_UK_neg_nutrients, PCW_1000 > 0)

# Change SACN variabel to a factor

df_UK_neg_nutrients_values$PCW_10000

df_UK_neg_nutrients_values$SACN_f <- factor(df_UK_neg_nutrients_values$SACN, levels = c("Oily", "Lean", "Shellfish"))

ggplot(df_UK_neg_nutrients_values, aes(Species, PCW_10000, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
  theme(legend.title = element_blank()) +
  facet_grid(.~SACN_f, scales = "free_x", space = "free_x") +
  theme(legend.position = "none") +
  scale_y_log10(breaks = c(seq(1,9,1), seq(10,90,10),seq(100,900,100), seq(1000,9000,1000), seq(10000, 100000, 10000)), 
                labels = c("1 g","","","","","","","","","10 g","","","","","","","","","100 g","","","","","",
                           "","","","1 kg","","","","","","","","","10000 kg", "","","","","","","","","100000 kg")) +
  theme(axis.text.y = element_text(color="#AA4499"))


# Cahnging the lo
ggplot(df_UK_neg_nutrients_values, aes(Species, PCW_10000, fill= Nutrient)) +
  geom_bar(position = "dodge", stat= "identity", color = "black") +
  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
  theme(legend.title = element_blank()) +
  facet_grid(.~SACN_f, scales = "free_x", space = "free_x") +
  theme(legend.position = "none") +
  scale_y_log10(breaks = c(seq(0.1,0.9,0.1), seq(1,9,1), seq(10,90,10),seq(100,900,100), seq(1000,9000,1000), seq(10000, 100000, 10000)), 
                labels = c("0.1 g","","","","","","","","","1 g","","","","","","","","","10 g","","","","","","","","","100 g","","","","","",
                           "","","","1 kg","","","","","","","","","10000 kg", "","","","","","","","","100000 kg")) +
  theme(axis.text.y = element_text(color="#AA4499"))









scale_y_log10(breaks = c(seq(1,9,1), seq(10,90,10),seq(100,900,100), seq(1000,9000,1000), 
                         seq(10000, 100000, 10000)), 
                         labels = c("1 µg","", "","","","","","","","10 µg","","","","","","","","",
                          "100 µg","","","","","","","","","1mg","","","","","","","","",
                          "10 mg","","","","","","","","","100 g")) +
  theme(axis.text.y = element_text(color="#44AA99"))


#ggplot(df_UK_neg_nutrients, aes(Species, PCW, fill= Nutrient)) +
#  geom_bar(position = "dodge", stat= "identity", color = "black") +
#  scale_x_discrete(name = "", guide = guide_axis(angle = 45)) +
#  scale_fill_manual(values = c("#AA4499", "#44AA99")) +
#  theme(legend.title = element_blank()) +
#  facet_grid(.~SACN_f, scales = "free_x", space = "free_x") +
#  theme(legend.position = "none") +
#  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
#                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 90000, 10000), seq(1000000, 10000000, 1000000)), 
#                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1 µg","",
#                           "","","","","","","","10 µg","","","","","","","","","100 µg","","","","","",
#                           "","","","1 mg","","","","","","","","","10 mg","","","","","","","","","100 g","","","","","","","","","1 kg")) +
  theme(axis.text.y = element_text(color="#AA4499"))


#  scale_y_log10(breaks = c(seq(0.01, 0.09, 0.01), seq(0.1, 0.9, 0.1), seq(1,9,1), seq(10,90,10),
#                           seq(100,900,100), seq(1000,9000,1000), seq(10000, 90000, 10000), seq(1000000, 10000000, 1000000)), 
#                labels = c("0.01","","","","","","","","","0.1","","","","","","","","","1","",
#                           "","","","","","","","10","","","","","","","","","100","","","","","",
#                           "","","","1000","","","","","","","","","10000","","","","","","","","","1000000","","","","","","","","","10000000"))
```



```{r Make key for pie chart}
c("#009E73", "#E69F00",  "#0072B2",  "#56B4E9", "#F0E442")
c("Imports", "Consumption", "Purchases", "Exports", "Production")
```

