---
title: "Laoding_HMRC-data-trial_DELETE-LATER"
author: "B. Scheliga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Loading Libraries, include=FALSE}
# It is good practice to load all needed libraries in the beginning of the scripted
#library(here)
library(tidyr)
library(tidyverse)
library(vroom) #for loading and transforming data
library(data.table) # for fread()-function

```

```{r Loading filepath to Raw data}
#Loading file path to project folder
source("Code/Data_filepath.R")# Data_filepath.R is listed in .gitignore-file. So, you will need to create that file yourself and provide your respected filepath using "data_dir <- [enter your here]"



```

```{r Loading HMRC data}
########### HMRC Trade Data

# Filepath to RawData 
filepath <- paste(data_dir,"RawData/csv-files", sep="") 
# reading the HRMC trade data dataset (.csv)
#df_HRMC_2009 <- vroom(file=paste(filepath,"HMRC_UK_trade-2009.csv", sep="/"))
vec_filenames_HMRC <- list.files(filepath, pattern = "HMRC_UK_trade", full.names = TRUE)



print("The following files were loaded:")
i = 1
# Loading the cleaned dataset
for(f in vec_filenames_HMRC){

    temp <- fread(f) # storing the data in a temporary 
    assign(paste("df_HMRC_",i,sep=""),temp) # assigning the df a name based on input dataset
    print(paste(i,". ",sub(paste(".*",filepath,sep=""),"",f),sep="")) # print out which dataset files had been used
    i = i+1
    rm(temp)# removing temp object
}
rm(i)

# Next step is to combine this all into big HMRC data.frame
df_HRMC_2009_to_2019 <- bind_rows(df_HMRC_1, df_HMRC_2, df_HMRC_3, df_HMRC_4, df_HMRC_5, df_HMRC_6)

rm(df_HMRC_1, df_HMRC_2, df_HMRC_3, df_HMRC_4, df_HMRC_5, df_HMRC_6) # removing the unneeded df






```

```{r loading EUMOFA data}
############### EUMOFA-file

#The EUMOFA-file with the commodity groups (CN8 code) will help us to easily identify fish for in "Non-Food use" and "Human consumption" in the HMRC-Trade data dataset.

# Filepath to EUMOFA-file with complete CN-8 codes
filepath <- paste(data_dir,"Methods/TradeData", sep="")
# reading the EUMOFA-file
df_EUMOFA_CN8 <- vroom(file=paste(filepath,"EUMOFA_CN-8-values.csv", sep="/"))
## Note: the CN8 codes are related to the respective year, and have change over time.

```


```{r preparing EUOFA CN8 data.frame}

# need to remove the space from the 'CN-8'-column. But leave it as character, so we don't loose the "0" at the beginning of the CN8 code
# https://stackoverflow.com/questions/20309876/r-how-to-replace-in-a-string

df_EUMOFA_CN8$`CN-8` <- gsub("\\ ","", df_EUMOFA_CN8$`CN-8`)

#df_EUMOFA_CN8_2009 <- df_EUMOFA_CN8 %>% filter(Year %in% "2009" )

print("FYI: In the EUMOFA CN-8 product name-Column are large - symbols, which R does not recognize replaces them with ? in a square")

```

```{r preparing HRMC trade data data.frame}

# Need to separate the CN8 code from the description in the CN8-column of the HMRC data
df_HRMC_2009_to_2019$Subset_aid_CN8 <- gsub(" .*$", "", df_HRMC_2009_to_2019$CN8) # subset string before white space

# Thanks to our psychic abilities, we know that one of the CN8-codes in the HRMC Uk trade is missing its lead 0. And we need to deal with that.  

# Check what will not be joined
df_HMRC_anti <- df_HRMC_2009_to_2019 %>% select('Net Mass (Kg)', 'Flow Type', 'Year','Month', 'Subset_aid_CN8', 'CN8') %>%  anti_join(.,df_EUMOFA_CN8, by = c('Subset_aid_CN8' = 'CN-8'))
#The following CN8 code items were not joined
unique(df_HMRC_anti$CN8)


```
It is item 2 "3074959", were we need to add a lead zero. 

```{r  preparing HRMC trade data data.frame}
# adding the lead 0 to "3074959" in the HRMC UK trade data
df_HRMC_2009_to_2019$Subset_aid_CN8 <- str_replace(df_HRMC_2009_to_2019$Subset_aid_CN8,"3074959","03074959")

# the "Flow Type" is also separate into "EU" and "Non-EU" Imports and Exports
df_HRMC_2009_to_2019$`Flow Type` <- str_replace(df_HRMC_2009_to_2019$`Flow Type`,"Non EU - ","") # needs to be first. Or else line 83 will remove "EU" from "Non EU -"
df_HRMC_2009_to_2019$`Flow Type` <- str_replace(df_HRMC_2009_to_2019$`Flow Type`,"EU - ","")


# Now, we can join the HMRC trade data and the EUMOFA data
df_HMRC_inner <- df_HRMC_2009_to_2019 %>% select('Net Mass (Kg)', 'Flow Type', 'Year','Month', 'Subset_aid_CN8') %>%  inner_join(.,df_EUMOFA_CN8, by = c('Subset_aid_CN8' = 'CN-8', 'Year' ))

```


```{r Calculating annual sum based on CN8 code / Species}
# calculating annual sum, selecting needed columns and converting to Net Mass from kg to 1000 tonnes
df_HRMC.sum <- df_HMRC_inner %>% group_by(CN8 = Subset_aid_CN8,`Product name` =`CN-8 product name`, Year = Year, Commodity =`Flow Type`, CF) %>% summarise(`Net Mass (1000 t)`= sum(`Net Mass (Kg)`)/1000000,`Net Mass (kg)`= sum(`Net Mass (Kg)`))

rm(df_HRMC_2009_to_2019,df_HMRC_inner)

df_HMRC_4DB <-df_HRMC.sum

```

```{r Defining FishType & Species from Product Name}
# Load FishTYpe and species
# use the grepl () function in a loop to add Fish type and Species 

<<<<<<< HEAD
# Filepath to EUMOFA-file with complete CN-8 codes
filepath <- paste(data_dir,"Methods", sep="")
# reading the EUMOFA-file
df_FishType_Species <- vroom(file=paste(filepath,"Species-and-Fish-Types.csv", sep="/"))
## Note: the CN8 codes are related to the respective year, and have change over time.
||||||| f818b58
=======
# Filepath to EUMOFA-file with complete CN-8 codes
filepath <- paste(data_dir,"Methods", sep="")
# reading the EUMOFA-file
df_FishType_Species <- vroom(file=paste(filepath,"Species_and_FishTypes.csv", sep="/"))
## Note: the CN8 codes are related to the respective year, and have change over time.
>>>>>>> b04769c3ede2856bb3d49d265ae1c5b7d6f9a074
df_HMRC_4DB$FishType <- NA
df_HMRC_4DB$Species  <- NA

<<<<<<< HEAD
df_test <- unique(df_EUMOFA_CN8[,c('CN-8','CN-8 product name')])
df_test$FishType <- NA
df_test$Species  <- NA




i=3
f=50
df_FishType_Species$Species[i]
df_test$`CN-8 product name`[f]


f=1
for(i in 1:length(df_FishType_Species$Species)){
  #print(paste("i =",i, sep = " "))
  for(f in 1:length(df_test$`CN-8`)){
    #print(paste("f =",f, sep = " "))
  if(grepl(df_FishType_Species$Species[i], 
        df_test$`CN-8 product name`[f],ignore.case = TRUE)){
    #print(paste(i, df_FishType_Species$Species[i], f,df_test$`CN-8 product name`[f], sep=" " ))
        df_test$Species[f] <- df_FishType_Species$Species[i] 
        df_test$FishType[f] <-  df_FishType_Species$FishType[i]
    }else{
     df_test$Species[f] <- "Not in list" 
    df_test$FishType[f] <-"Not in list"
        }
    }
  }



#ifelse(grepl(df_FishType_Species$Species,ignore.case = TRUE, 
#df_HMRC_4DB$`Product name`), df_test$FishType  , NA)
  
 # apply(data, 1, function(x) {ifelse(any(x == 0), NA, length(unique(x)))})



#df_HMRC_4DB$FishType <- NA
#df_HMRC_4DB$Species  <- NA

||||||| f818b58
=======
df_test <- df_HMRC_4DB




#i=1
#f=141


#f=1
#for(i in length(df_FishType_Species$Species)){
#  for(f in length(df_test$CN8)){
#  if(grepl(df_FishType_Species$Species[i],ignore.case = TRUE, 
#df_HMRC_4DB$`Product name`[f])){
#    df_test$Species[f] <- df_FishType_Species$Species[i] 
#    df_test$FishType[f] <-  df_FishType_Species$FishType[i]
#    }else{
#     df_test$Species[f] <- "Not in list" 
#    df_test$FishType[f] <-"Not in list"
#        }
#    }
#  }



#ifelse(grepl(df_FishType_Species$Species,ignore.case = TRUE, 
#df_HMRC_4DB$`Product name`), df_test$FishType  , NA)
  
 # apply(data, 1, function(x) {ifelse(any(x == 0), NA, length(unique(x)))})



#df_HMRC_4DB$FishType <- NA
#df_HMRC_4DB$Species  <- NA

>>>>>>> b04769c3ede2856bb3d49d265ae1c5b7d6f9a074
```



```{r Adding column needed for data base}

# Adding DataSupplier information
df_HMRC_4DB$DataSupplier <- "HMRC"
df_HMRC_4DB$DataSet <- "HMRC Overseas Trade data table - UK Trade Info"
#determining if the Fish is for Human consumption or not based on the CF from the EUMOFA-file
df_HMRC_4DB$Intention <- ifelse(df_HMRC_4DB$CF == 0, "Non food uses", "Human consumption") 
df_HMRC_4DB <- rename(df_HMRC_4DB, Value =`Net Mass (1000 t)`)
df_HMRC_4DB$Units <- "1000 tonnes"
df_HMRC_4DB$TemporalResolution <- "Annual"
df_HMRC_4DB$Flag <- ifelse(df_HMRC_4DB$CF <= 1, "EXAMPLES: UC, FiTyAlig", "UC, FiTyAlig, ?????")
df_HMRC_4DB$FlagDescription <- ifelse(df_HMRC_4DB$CF <= 1, "EXAMPLES:Units changed, Fish type aligned ", "Units changed, Fish type aligned, weight values converted using ?????")


```


```{r Selecting Columns and Saving to .csv}
df_HMRC_4DB <- df_HMRC_4DB %>% ungroup %>%  select(DataSupplier, DataSet, Commodity, Intention, FishType, Species, Value, Units, Year, TemporalResolution, Flag, FlagDescription)




```

